spring.application.name=fade
spring.datasource.url=jdbc:mysql://localhost:3306/fade
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
application.security.jwt.secret-key = ksadjxmcaslk341kjfsaklcj2334thisismysecretsuperlonglonglonglongkey
springdoc.swagger-ui.path=/swagger
app.jwt.issuer=Fade_Issuer
app.jwt.audience=Fade_Client
app.jwt.expiration-in-ms=86400000
file.upload-dir=D:/uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.data.redis.host=localhost
spring.data.redis.port=6379
